apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-secure-cloud-run-security-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Secure Cloud Run Security
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run.git
      sourceType: git
      dir: /modules/secure-cloud-run-security
  ui:
    input:
      variables:
        decrypters:
          name: decrypters
          title: Decrypters
        encrypters:
          name: encrypters
          title: Encrypters
        folder_id:
          name: folder_id
          title: Folder Id
        groups:
          name: groups
          title: Groups
        key_name:
          name: key_name
          title: Key Name
        key_protection_level:
          name: key_protection_level
          title: Key Protection Level
        key_rotation_period:
          name: key_rotation_period
          title: Key Rotation Period
        keyring_name:
          name: keyring_name
          title: Keyring Name
        kms_project_id:
          name: kms_project_id
          title: Kms Project Id
        location:
          name: location
          title: Location
        organization_id:
          name: organization_id
          title: Organization Id
        owners:
          name: owners
          title: Owners
        policy_for:
          name: policy_for
          title: Policy For
        prevent_destroy:
          name: prevent_destroy
          title: Prevent Destroy
        serverless_project_id:
          name: serverless_project_id
          title: Serverless Project Id
