# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-secure-cloud-run-core
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Secure Cloud Run Core
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run.git
      sourceType: git
      dir: /modules/secure-cloud-run-core
    version: 0.23.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: cloud_run_vpc_connector
        location: examples/cloud_run_vpc_connector
      - name: job_service_account_creation
        location: examples/job_service_account_creation
      - name: secure_cloud_run
        location: examples/secure_cloud_run
      - name: secure_cloud_run_standalone
        location: examples/secure_cloud_run_standalone
      - name: secure_cloud_run_standalone_direc t_egress
        location: examples/secure_cloud_run_standalone_direc t_egress
      - name: simple_cloud_run
        location: examples/simple_cloud_run
      - name: simple_cloud_run_with_cmek
        location: examples/simple_cloud_run_with_cmek
      - name: simple_job_exec
        location: examples/simple_job_exec
      - name: v2
        location: examples/v2
      - name: v2_with_gmp
        location: examples/v2_with_gmp
      - name: v2_with_gpu
        location: examples/v2_with_gpu
      - name: v2_with_iap
        location: examples/v2_with_iap
  interfaces:
    variables:
      - name: project_id
        description: The project where cloud run is going to be deployed.
        varType: string
        required: true
      - name: location
        description: The location where resources are going to be deployed.
        varType: string
        required: true
      - name: region
        description: Location for load balancer and Cloud Run resources (usually same as location).
        varType: string
        required: true
      - name: service_name
        description: The name of the Cloud Run service to create.
        varType: string
        required: true
      - name: image
        description: GAR hosted image URL to deploy.
        varType: string
        required: true
      - name: cloud_run_sa
        description: Service account to be used on Cloud Run.
        varType: string
        required: true
      - name: execution_environment
        description: The execution environment (e.g., EXECUTION_ENVIRONMENT_GEN2, EXECUTION_ENVIRONMENT_GEN1).
        varType: string
        defaultValue: EXECUTION_ENVIRONMENT_GEN2
      - name: env_vars
        description: Environment variables.
        varType: |-
          list(object({
              value = string
              name  = string
            }))
        defaultValue: []
      - name: ports
        description: Port which the container listens to.
        varType: |-
          object({
              name = string
              port = number
            })
        defaultValue:
          name: http1
          port: 8080
      - name: argument
        description: Arguments passed to the ENTRYPOINT command.
        varType: list(string)
        defaultValue: []
      - name: container_command
        description: Container entrypoint command.
        varType: list(string)
        defaultValue: []
      - name: limits
        description: Resource limits (memory, cpu, nvidia.com/gpu).
        varType: map(string)
      - name: requests
        description: "Resource requests (memory, cpu). Note: Child module must be patched to support this field."
        varType: map(string)
        defaultValue: {}
      - name: container_concurrency
        description: Concurrent request limits to the service.
        varType: number
      - name: timeout_seconds
        description: Timeout for each request in seconds.
        varType: number
        defaultValue: 120
      - name: startup_probe
        description: Configuration for the startup probe.
        varType: |-
          object({
              failure_threshold     = optional(number)
              initial_delay_seconds = optional(number)
              timeout_seconds       = optional(number)
              period_seconds        = optional(number)
              http_get = optional(object({
                path = optional(string)
                port = optional(number)
                http_headers = optional(list(object({
                  name  = string
                  value = string
                })))
              }))
              tcp_socket = optional(object({
                port = number
              }))
              grpc = optional(object({
                port    = optional(number)
                service = optional(string)
              }))
            })
      - name: liveness_probe
        description: Configuration for the liveness probe.
        varType: |-
          object({
              failure_threshold     = optional(number)
              initial_delay_seconds = optional(number)
              timeout_seconds       = optional(number)
              period_seconds        = optional(number)
              http_get = optional(object({
                path = optional(string)
                port = optional(number)
                http_headers = optional(list(object({
                  name  = string
                  value = string
                })))
              }))
              tcp_socket = optional(object({
                port = number
              }))
              grpc = optional(object({
                port    = optional(number)
                service = optional(string)
              }))
            })
      - name: ingress
        description: Ingress traffic sources allowed to call the service.
        varType: string
        defaultValue: INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER
      - name: vpc_connector_id
        description: VPC Connector id. If provided, Direct VPC Egress settings are ignored.
        varType: string
      - name: vpc_egress_value
        description: Sets VPC Egress firewall rule (e.g. PRIVATE_RANGES_ONLY, ALL_TRAFFIC).
        varType: string
        defaultValue: PRIVATE_RANGES_ONLY
      - name: vpc_network_interface
        description: List of network interfaces for Direct VPC Egress (Cloud Run v2).
        varType: |-
          object({
              network    = optional(string)
              subnetwork = optional(string)
              tags       = optional(list(string))
            })
      - name: encryption_key
        description: CMEK encryption key self-link.
        varType: string
      - name: lb_name
        description: Name for load balancer and associated resources.
        varType: string
        defaultValue: tf-cr-lb
      - name: create_cloud_armor_policies
        description: When true, create Cloud Armor policies. When false, provide existing name.
        varType: bool
        defaultValue: true
      - name: cloud_armor_policies_name
        description: Existing Cloud Armor policy name if create_cloud_armor_policies is false.
        varType: string
      - name: default_rules
        description: Default rule for Cloud Armor.
        varType: |-
          map(object({
              action         = string
              priority       = string
              versioned_expr = string
              src_ip_ranges  = list(string)
              description    = string
            }))
        defaultValue:
          default_rule:
            action: allow
            description: Default allow all rule
            priority: "2147483647"
            src_ip_ranges:
              - "*"
            versioned_expr: SRC_IPS_V1
      - name: owasp_rules
        description: Additional Cloud Armor rules (SQLi, XSS, etc).
        varType: |-
          map(object({
              action     = string
              priority   = string
              expression = string
            }))
        defaultValue:
          rule_canary:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('rce-v33-stable')
            priority: "1003"
          rule_lfi:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('lfi-v33-stable')
            priority: "1002"
          rule_protocolattack:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('protocolattack-v33-stable')
            priority: "1006"
          rule_rfi:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('rfi-v33-stable')
            priority: "1004"
          rule_scannerdetection:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('scannerdetection-v33-stable')
            priority: "1005"
          rule_sessionfixation:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('sessionfixation-v33-stable')
            priority: "1007"
          rule_sqli:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('sqli-v33-stable')
            priority: "1000"
          rule_xss:
            action: deny(403)
            expression: evaluatePreconfiguredExpr('xss-v33-stable')
            priority: "1001"
      - name: ssl_certificates
        description: A object with a list of domains to auto-generate SSL certificates or a list of SSL Certificates self-links.
        varType: |-
          object({
              ssl_certificates_self_links       = list(string)
              generate_certificates_for_domains = list(string)
            })
        required: true
      - name: volume_mounts
        description: Volume Mounts to be attached to the container.
        varType: |-
          list(object({
              mount_path = string
              name       = string
            }))
        defaultValue: []
      - name: volumes
        description: "[Beta] Volumes needed for environment variables (when using secret)."
        varType: |-
          list(object({
              name = string
              secret = set(object({
                secret_name = string
                items       = map(string)
              }))
            }))
        defaultValue: []
      - name: generate_revision_name
        description: Option to enable revision name generation.
        varType: bool
        defaultValue: true
      - name: min_scale_instances
        description: Minimum number of container instances.
        varType: number
        defaultValue: 0
      - name: max_scale_instances
        description: Maximum number of container instances.
        varType: number
        defaultValue: 100
      - name: traffic_split
        description: Managing traffic routing to the service.
        varType: |-
          list(object({
              latest_revision = optional(bool)
              percent         = number
              revision_name   = optional(string)
              tag             = optional(string)
            }))
        defaultValue:
          - latest_revision: true
            percent: 100
      - name: members
        description: Users/SAs to be given invoker access.
        varType: list(string)
        defaultValue: []
      - name: iap_members
        description: Users/SAs to be given IAP access (if IAP is enabled).
        varType: list(string)
        defaultValue: []
      - name: service_labels
        description: Labels to assign to the service.
        varType: map(string)
        defaultValue: {}
      - name: template_labels
        description: Labels to assign to the container metadata.
        varType: map(string)
        defaultValue: {}
      - name: verified_domain_name
        description: List of custom Domain Name.
        varType: list(string)
        defaultValue: []
      - name: force_override
        description: Option to force override existing mapping.
        varType: bool
        defaultValue: false
      - name: certificate_mode
        description: The mode of the certificate (NONE or AUTOMATIC).
        varType: string
        defaultValue: NONE
      - name: domain_map_labels
        description: Labels to assign to the Domain mapping.
        varType: map(string)
        defaultValue: {}
      - name: domain_map_annotations
        description: Annotations to the domain map.
        varType: map(string)
        defaultValue: {}
      - name: cloud_run_deletion_protection
        description: This field prevents Terraform from destroying or recreating the Cloud Run v2 Jobs and Services
        varType: bool
        defaultValue: false
      - name: enable_prometheus_sidecar
        description: Enable Prometheus sidecar in Cloud Run instance.
        varType: bool
        defaultValue: false
      - name: gpu_zonal_redundancy_disabled
        description: True if GPU zonal redundancy is disabled on this revision.
        varType: bool
        defaultValue: false
      - name: node_selector
        description: Node Selector describes the hardware requirements of the GPU resource. [More info](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service#nested_template_node_selector).
        varType: |-
          object({
              accelerator = string
            })
      - name: launch_stage
        description: The launch stage as defined by Google Cloud Platform Launch Stages. Cloud Run supports ALPHA, BETA, and GA. If no value is specified, GA is assumed.
        varType: string
        defaultValue: GA
    outputs:
      - name: domain_map_id
        description: Unique Identifier for the created domain map.
      - name: domain_map_status
        description: Status of Domain mapping.
      - name: load_balancer_ip
        description: IP Address used by Load Balancer.
      - name: revision
        description: Deployed revision for the service.
      - name: service_id
        description: Unique Identifier for the created service.
      - name: service_status
        description: Status of the created service.
      - name: service_url
        description: The URL on which the deployed service is available.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/artifactregistry.admin
          - roles/iam.serviceAccountUser
          - roles/serviceusage.serviceUsageViewer
          - roles/cloudkms.admin
          - roles/resourcemanager.projectIamAdmin
          - roles/run.admin
          - roles/iam.serviceAccountAdmin
    services:
      - accesscontextmanager.googleapis.com
      - cloudbilling.googleapis.com
      - cloudkms.googleapis.com
      - cloudresourcemanager.googleapis.com
      - compute.googleapis.com
      - iam.googleapis.com
      - iap.googleapis.com
      - monitoring.googleapis.com
      - run.googleapis.com
      - serviceusage.googleapis.com
      - storage-api.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 6, < 8"
      - source: hashicorp/google-beta
        version: ">= 6, < 8"
      - source: hashicorp/random
        version: < 4.0
      - source: hashicorp/time
        version: < 1.0
