# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-v-2-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Cloud Run v2 Service
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run.git
      sourceType: git
      dir: /modules/v2
  ui:
    input:
      variables:
        binary_authorization:
          name: binary_authorization
          title: Binary Authorization
        client:
          name: client
          title: Client
        cloud_run_deletion_protection:
          name: cloud_run_deletion_protection
          title: Cloud Run Deletion Protection
          level: 1
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: false
        containers:
          name: containers
          title: Containers
          properties:
            container_image:
              name: container_image
              title: Container Image
              regexValidation: ^((([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}(:[0-9]+)?/)?([a-z0-9]+([._-][a-z0-9]+)*/)*[a-z0-9]+([._-][a-z0-9]+)*(:(\w[\w.-]{0,127})|@sha256:[a-fA-F0-9]{64})?)$
              validation: Must be a valid Docker image (lowercase repo, optional registry, tag, or SHA256 digest)
            volume_mounts:
              name: volume_mounts
              title: Volume Mounts
              subtext: Mount In-memory, Network File System, Secret and Cloud Storage bucket volumes to your container
            resources:
              name: resources
              title: Resources
              properties:
                limits:
                  name: limits
                  title: Limits
                  properties:
                    cpu:
                      name: cpu
                      title: CPU
                      subtext: Number of vCPUs allocated to each instance of this container
                    memory:
                      name: memory
                      title: Memory
                      subtext: Memory to allocate to each instance of this container
            startup_probe:
              name: startup_probe
              title: Startup Probe
              properties:
                failure_threshold:
                  name: failure_threshold
                  title: Failure Threshold
                  subtext: Number of times to retry the probe before marking the container as Unready
                  min: 1
                  max: 2147483647
                  validation: Choose an integer value between 1 and 2147483647
                initial_delay_seconds:
                  name: initial_delay_seconds
                  title: Initial Delay Seconds
                  subtext: Number of seconds after the container has started before performing the first probe. Enter an integer value between 0 and 240
                  min: 0
                  max: 240
                  validation: Enter an integer value between 0 and 240
                timeout_seconds:
                  name: timeout_seconds
                  title: Timeout Seconds
                  subtext: Number of seconds after which the probe times out. This value shouldn't exceed Period seconds. Enter an integer value between 1 and 240
                  min: 1
                  max: 240
                  validation: Enter an integer value between 1 and 240
                period_seconds:
                  name: period_seconds
                  title: Period Seconds
                  subtext: Number of seconds to wait between starting a probe attempt. Enter an integer value between 1 and 240
                  min: 1
                  max: 240
                  validation: Enter an integer value between 1 and 240
                http_get:
                  name: http_get
                  title: Http Get
                  properties:
                    get:
                      name: get
                      title: Get
                      subtext: "Path to access on the HTTP server. Ex: e.g./reddy"
                    port:
                      name: port
                      title: Port
                      subtext: Port to make a connection for the Cloud Run instance. It will default to the container port, whose default value is 8080
                      min: 1
                      max: 65535
                      validation: Choose an integer value between 1 and 65535
                    http_headers:
                      name: http_headers
                      title: Http Headers
                      subtext: Custom headers to set in the request. HTTP allows repeated headers
                tcp_socket:
                  name: tcp_socket
                  title: TCP Socket
                  subtext: Port to make a connection for the Cloud Run instance. It will default to the container port, whose default value is 8080
                grpc:
                  name: grpc
                  title: GRPC
                  properties:
                    port:
                      name: port
                      title: Port
                      subtext: Port to make a connection for the Cloud Run instance. It will default to the container port, whose default value is 8080.
            liveness_probe:
              name: liveness_probe
              title: Liveness Probe
              properties:
                failure_threshold:
                  name: failure_threshold
                  title: Failure Threshold
                  subtext: Number of seconds after the container has started before performing the first probe. Enter an integer value between 0 and 3600
                initial_delay_seconds:
                  name: initial_delay_seconds
                  title: Initial Delay Seconds
                  subtext: Number of times to retry the probe before marking the container as Unready
                timeout_seconds:
                  name: timeout_seconds
                  title: Timeout Seconds
                  subtext: Number of times to retry the probe before marking the container as Unready
                period_seconds:
                  name: period_seconds
                  title: Period Seconds
                  subtext: Number of seconds to wait between starting a probe attempt. Enter an integer value between 1 and 3600
                http_get:
                  name: http_get
                  title: Http Get
                  properties:
                    path:
                      name: path
                      title: Path
                      subtext: Path to access on HTTP server
                    port:
                      name: port
                      title: Port
                      subtext: Port to make connection for the Cloud Run instance. It will default to container port which is 8080
                    http_headers:
                      name: http_headers
                      title: Http Headers
                      subtext: Custom Headers to set in the request. HTTP allows repeated headers.
            ports:
              name: ports
              title: Ports
              properties:
                name:
                  name: name
                  title: Name
                  regexValidation: ^[a-z0-9.-]*$
                  validation: Name may contain lowercase letters, numbers, hyphens or dots
                container_port:
                  name: container_port
                  title: Container Port
                  subtext: Requests will be sent to the container on this port
                  min: 1
                  max: 65535
                  validation: Choose an integer value between 1 and 65535
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                - container_name: service-container
                  container_image: us-docker.pkg.dev/cloudrun/container/hello
                  ports:
                    container_port: 8080
                  startup_probe:
                    failure_threshold: 3
                    initial_delay_seconds: 0
                    period_seconds: 10
                  liveness_probe:
                    failure_threshold: 0
                    initial_delay_seconds: 3
                    timeout_seconds: 3
                    period_seconds: 10
                    http_get:
                      path: Path (e.g./.ready)
                      port: 8080
                    grpc:
                      port: 8080
        create_service_account:
          name: create_service_account
          title: Create Service Account
          level: 1
        custom_audiences:
          name: custom_audiences
          title: Custom Audiences
        description:
          name: description
          title: Description
          level: 1
          regexValidation: ^[\s\S]{0,512}$
          validation: This field currently has a 512-character limit.
        enable_prometheus_sidecar:
          name: enable_prometheus_sidecar
          title: Enable Prometheus Sidecar
          level: 1
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: true
        encryption_key:
          name: encryption_key
          title: Encryption Key
          level: 1
        execution_environment:
          name: execution_environment
          title: Execution Environment
          level: 1
          enumValueLabels:
            - label: EXECUTION_ENVIRONMENT_GEN2
              value: EXECUTION_ENVIRONMENT_GEN2
            - label: EXECUTION_ENVIRONMENT_GEN1
              value: EXECUTION_ENVIRONMENT_GEN1
        iap_members:
          name: iap_members
          title: Iap Members
          level: 1
          regexValidation: ^(?:allUsers|allAuthenticatedUsers)$|^((?:user|group|serviceAccount):(?:[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})|(?:domain:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,})|(?:projectOwner|projectEditor|projectViewer):[a-z][a-z0-9-]{0,28}[a-z0-9])$
          validation: Must be allUsers, allAuthenticatedUsers, or a service account in the format serviceAccount:email@example.com. [More info](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iap_web_cloud_run_service_iam#member\/members-2).
        ingress:
          name: ingress
          title: Ingress
          level: 1
          enumValueLabels:
            - label: INGRESS_TRAFFIC_ALL
              value: INGRESS_TRAFFIC_ALL
            - label: INGRESS_TRAFFIC_INTERNAL_ONLY
              value: INGRESS_TRAFFIC_INTERNAL_ONLY
            - label: INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER
              value: INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER
        launch_stage:
          name: launch_stage
          title: Launch Stage
        location:
          name: location
          title: Location
        max_instance_request_concurrency:
          name: max_instance_request_concurrency
          title: Max Instance Request Concurrency
          level: 1
        members:
          name: members
          title: Members
          regexValidation: ^(?:allUsers|allAuthenticatedUsers)$|^((?:user|group|serviceAccount):(?:[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})|(?:domain:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,})|(?:projectOwner|projectEditor|projectViewer):[a-z][a-z0-9-]{0,28}[a-z0-9])$
          validation: Must be allUsers, allAuthenticatedUsers, or a service account in the format serviceAccount:email@example.com. [More info](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service_iam#member\/members-1).
          level: 1
        project_id:
          name: project_id
          title: Project Id
        revision:
          name: revision
          title: Revision
          level: 1
        service_account:
          name: service_account
          title: Service Account
        service_account_project_roles:
          name: service_account_project_roles
          title: Service Account Project Roles
          level: 1
        service_annotations:
          name: service_annotations
          title: Service Annotations
        service_labels:
          name: service_labels
          title: Service Labels
        service_name:
          name: service_name
          title: Service Name
          regexValidation: ^[a-z][a-z0-9-]{0,47}[a-z0-9]$
          validation: Use lowercase letters, numbers, and hyphens. Start with a letter and end with letter/number. Must be 49 characters or fewer.
        service_scaling:
          name: service_scaling
          title: Service Scaling
          level: 1
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                min_intance_count: 0
        session_affinity:
          name: session_affinity
          title: Session Affinity
          level: 1
          enumValueLabels:
            - label: "true"
              value: "true"
            - label: "false"
              value: "false"
        template_annotations:
          name: template_annotations
          title: Template Annotations
        template_labels:
          name: template_labels
          title: Template Labels
        template_scaling:
          name: template_scaling
          title: Template Scaling
          level: 1
          properties:
            min_instance_count:
              name: min_instance_count
              title: Min Instance Count
              subtext: The service minimum instances is preferable for most use-cases. Only use this setting if you specifically require a per-revision setting
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                min_instance_count: 0
                max_instance_count: 100
        timeout:
          name: timeout
          title: Timeout
        traffic:
          name: traffic
          title: Traffic
        volumes:
          name: volumes
          title: Volumes
          subtext: After creating a volume, navigate to the Container’s section to mount it to a container
          properties:
            name:
              name: name
              title: Name
              regexValidation: ^[a-zA-Z0-9_-]*$
              validation: Volume name must only contain alphanumeric characters, hyphens and underscores
            secret:
              name: secret
              title: Secret
              properties:
                items:
                  name: items
                  title: Items
                  properties:
                    path:
                      name: path
                      title: Path
                      subtext: "Example format (parent secret): \"projects/project-number/secrets/secret-name\""
            nfs:
              name: nfs
              title: NFS
              properties:
                server:
                  name: server
                  title: Server
                  subtext: The IP address or domain of your NFS server
                path:
                  name: path
                  title: Path
                  subtext: The path to the NFS server directory you want to mount
        vpc_access:
          name: vpc_access
          title: Vpc Access
          level: 1
          properties:
            egress:
              name: egress
              title: Egress
              subtext: Traffic VPC egress settings.
              enumValueLabels:
                - label: ALL_TRAFFIC
                  value: ALL_TRAFFIC
                - label: PRIVATE_RANGES_ONLY
                  value: PRIVATE_RANGES_ONLY
            connector:
              name: connector
              title: Connector
              subtext: VPC Access connector name.
              regexValidation: ^projects/(?:[a-z][a-z0-9-]*[a-z0-9]|[0-9]+)/locations/([a-z0-9-]+)/connectors/([a-z][a-z0-9-]*[a-z0-9])$
              validation: Invalid connector name. It must be in the format projects/{project}/locations/{location}/connectors/{connector}
            network_interfaces:
              name: network_interfaces
              title: Network Interfaces
              subtext: Direct VPC egress settings. Currently only single network interface is supported.
              toggleUsingVariables:
                - variableName: vpc_access.connector
              properties:
                network:
                  name: network
                  title: Network
                  subtext: The VPC network that the Cloud Run resource will be able to send traffic to.
                subnetwork:
                  name: subnetwork
                  title: Subnetwork
                  subtext: The VPC subnetwork that the Cloud Run resource will get IPs from. At least one of network or subnetwork must be specified. If both network and subnetwork are specified, the given VPC subnetwork must belong to the given VPC network. If subnetwork is not specified, the subnetwork with the same name with the network will be used.
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                egress: ALL_TRAFFIC
                network_interfaces:
                  network: default
                  subnetwork: default
    runtime:
      outputs:
        service_uri:
          visibility: VISIBILITY_ROOT
