apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Cloud Run v2 Service
    source:
      repo: https://github.com/yogitaupadhyay/terraform-google-cloud-run.git
      sourceType: git
      dir: /modules/v2
  ui:
    input:
      variables:
        binary_authorization:
          name: binary_authorization
          title: Binary Authorization
        client:
          name: client
          title: Client
        cloud_run_deletion_protection:
          name: cloud_run_deletion_protection
          title: Cloud Run Deletion Protection
        containers:
          name: containers
          title: Containers
        create_service_account:
          name: create_service_account
          title: Create Service Account
        custom_audiences:
          name: custom_audiences
          title: Custom Audiences
        description:
          name: description
          title: Description
        enable_prometheus_sidecar:
          name: enable_prometheus_sidecar
          title: Enable Prometheus Sidecar
        encryption_key:
          name: encryption_key
          title: Encryption Key
        execution_environment:
          name: execution_environment
          title: Execution Environment
        ingress:
          name: ingress
          title: Ingress
        launch_stage:
          name: launch_stage
          title: Launch Stage
        location:
          name: location
          title: Location
        max_instance_request_concurrency:
          name: max_instance_request_concurrency
          title: Max Instance Request Concurrency
        members:
          name: members
          title: Members
        project_id:
          name: project_id
          title: Project Id
        revision:
          name: revision
          title: Revision
        service_account:
          name: service_account
          title: Service Account
        service_account_project_roles:
          name: service_account_project_roles
          title: Service Account Project Roles
        service_annotations:
          name: service_annotations
          title: Service Annotations
        service_labels:
          name: service_labels
          title: Service Labels
        service_name:
          name: service_name
          title: Service Name
        service_scaling:
          name: service_scaling
          title: Service Scaling
        session_affinity:
          name: session_affinity
          title: Session Affinity
        template_annotations:
          name: template_annotations
          title: Template Annotations
        template_labels:
          name: template_labels
          title: Template Labels
        template_scaling:
          name: template_scaling
          title: Template Scaling
        timeout:
          name: timeout
          title: Timeout
        traffic:
          name: traffic
          title: Traffic
        volumes:
          name: volumes
          title: Volumes
        vpc_access:
          name: vpc_access
          title: Vpc Access
