apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-run-v-2
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Cloud Run v2 Service
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-run.git
      sourceType: git
      dir: /modules/v2
    version: 0.12.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  ui:
    input:
      variables:
    outputs:
        service_uri:
          openInNewTab: false
          showInNotification: false
          label: Service URI for Application
          visibility: Visibility.VISIBILITY_ROOT
